name: Generate Predictions and Graphs

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  generate_predictions_and_graphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt 
      - run: python github_action.py
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions"
      - run: git add .
      - run: git commit -m "Automated Commit"
      - run: git push origin main
